# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://yupengzte.github.io
date_format: "ordinal"
title: 山水过处
subtitle: "若无闲事挂心头 便是人间好时节"
description: "余鹏的个人博客"
keywords: ANDY
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Yu Peng
organization: 
organization_url: 
location: Shanghai, China
email: 

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: yupengzte/yupengzte.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: yupengzte
#douban_username: yupengzte#
#facebook_username: yupengzte#
#weibo_username: yupengzte#
#zhihu_username: yupengzte#
#twitter_username: yupengzte#

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
# https://disqus.com
#disqus:
#   username: yupeng717
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: YuPengZTE
#    repo: blog-comments
#    oauth:
#        client_id: 762dda0c1827d8d15f53
#        client_secret: 8e6d1f4e2f42c7db02e97a0a5abd30e1695bce82
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: YuPengZTE
    repo: blog-comments
    clientID: 762dda0c1827d8d15f53
    clientSecret: 8e6d1f4e2f42c7db02e97a0a5abd30e1695bce82
#disqus_username: yupeng717#
# 在使用其它评论组件时可点击显示 Disqus
#lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-92538560-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [C, C++, Java, Python, Go]
