# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://yu3peng.github.io
date_format: "ordinal"
title: Yu Peng
subtitle: "若无闲事挂心头 便是人间好时节"
description: "个人博客"
keywords: yupeng
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Yu Peng
organization: 
organization_url: 
location: Shanghai, China
email: 

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#  -
#    href: /wiki/
#    label: 维基
#
  -
    href: /note/
    label: 笔记

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    note:
        output: true
        permalink: /note/:path/

repository: yu3peng/yu3peng.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: yu3peng
#douban_username: yu3peng#
#facebook_username: yu3peng#
#weibo_username: yu3peng#
#zhihu_username: yu3peng#
#twitter_username: yu3peng#

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
# https://disqus.com
#disqus:
#   username: yupeng717
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: yu3peng
    repo: blog-comments
    oauth:
        client_id: b2ad054f2e4daf7ad564
        client_secret: c742e4086336e58b70e0e88dc791e5bce6e37330
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: yu3peng
    repo: blog-comments
    clientID: b2ad054f2e4daf7ad564
    clientSecret: c742e4086336e58b70e0e88dc791e5bce6e37330
#disqus_username: yupeng717#
# 在使用其它评论组件时可点击显示 Disqus
#lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-170170785-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [/]
